### ISSUE TITLE
Invalid or unexpected token

### ISSUE THREAD

**Issue by alchemistgo87** [bfriel/crunchy-vs-smooth#1]
First of all, thank you for this wonderful and informative tutorial. The issue I am facing is:

Completed all the steps till the creation of node server with index.js file in the root directory.  
But when running the command `node index.js` getting this error:
```
SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by bfriel** [comment]
Hi @alchemistgo87 thanks for your note. Do you have a link to your code repo so that I can take a look?
